# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name: "edfward"

title: edfward's blog
email: edfward@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An Inquiry into Values
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.edfward.com" # the base hostname & protocol for your site
twitter_username: edfward
github_username:  edfward

markdown: kramdown

kramdown:
  input: GFM

exclude: ["*.bak", "*.sh", "_drafts/", "about.md"]

# URL
baseurl:            ""

# Navigation
nav:
  - name:           "(cont.)"
    href:           "https://junjiah.com"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
